### ISSUE TITLE
react-native-paper

### ISSUE THREAD

**Issue by lumberman** [srk-sharingan/sharingan-rn-modal-dropdown#14]
Error: Unable to resolve module react-native-paper

It seems overkill to pull react-native-paper library to have custom dropdown component?

**Comment by srk-sharingan** [comment]
Yes, I agree.
But I created this dropdown extension for react-native-paper. Also, some of the react-native-paper components are reused in this like chips and icons.
Maybe I should mention clearly this components extension for react-native-paper.

**Comment by srk-sharingan** [comment]
Since this component developed using most of the react-native-paper components making it clear in the readme file that this component is an extension for the react-native-paper
