### ISSUE TITLE
Option to disable chips in multiselect dropdown

### ISSUE THREAD

**Issue by SaadAhmadSaddiqui** [srk-sharingan/sharingan-rn-modal-dropdown#17]
**Is your feature request related to a problem? Please describe.**
I want to display the chips in my own way and not in the scroll row fashion it is implemented

**Describe the solution you'd like**
Option to disable the chips in the Multi Select Dropdown.

**Describe alternatives you've considered**
I tried using the simple dropdown and use my own method of showing chips, but I really need the multiselect option so simple dropdown is not feasible.

**Comment by srk-sharingan** [comment]
What do you mean by the option for disabling the Chips? Only the chip UI or the entire chip UI with selected value?

**Comment by SaadAhmadSaddiqui** [comment]
Only the chip UI. I just want to get the values from the multi select dropdown. I'll display chips on my own in a separate place.

**Comment by srk-sharingan** [comment]
You mean to say that you don't need the Horizontal scroll list itself.

**Comment by SaadAhmadSaddiqui** [comment]
Yes, that's right.

**Comment by srk-sharingan** [comment]
Hmmm, I Will enable prop for that :)

**Comment by srk-sharingan** [comment]
Use the below prop:
 hideChip - Hide multi-select dropdown chip
