### ISSUE TITLE
Option to change tick and down arrow

### ISSUE THREAD

**Issue by SaadAhmadSaddiqui** [srk-sharingan/sharingan-rn-modal-dropdown#18]
**Is your feature request related to a problem? Please describe.**
Color of the tick and the dropdown is different than the rest of my layout.

**Describe the solution you'd like**
Option to change color of the tick or pass a custom tick component. Also the down arrow on the input.

**Describe alternatives you've considered**

**Additional context**

**Comment by srk-sharingan** [comment]
Hello, @SaadAhmadSaddiqui  there is prop **primaryColor** if you set color here that will help to change the color for both the dropdown arrow and for the tick mark.

**Comment by SaadAhmadSaddiqui** [comment]
Ah alright. Thanks!

**Comment by SaadAhmadSaddiqui** [comment]
But I was also hoping to maybe pass a custom JSX.Element down to the arrow and the tick to make it more customizable.

**Comment by srk-sharingan** [comment]
Ummm, I get it. I'll look into that.

**Comment by sorioinc** [comment]
@srk-sharingan thanks for this component, it has been a life saver. Have you had a chance to look into adding a custom tick icon?

**Comment by srk-sharingan** [comment]
Use the below props:
Prop: dropdownIcon - Change dropdown icon -> material design icon
Prop: itemSelectIcon - Change dropdown item select icon -> Custome react node or material design icon
