### ISSUE TITLE
styles options

### ISSUE THREAD

**Issue by zhrht** [srk-sharingan/sharingan-rn-modal-dropdown#19]
I'm having a difficulties in controlling the style of the dropdown list like adding full border or changing border color etc.., and I tried to use the attached props to change the style but it didn't work for me, there's no clear documentation of how to correctly design or change the style of the dropdown lists.
please  give me some examples on how to control the style. 
thank you.

**Comment by srk-sharingan** [comment]
Take a look at the [example](https://github.com/srk-sharingan/sharingan-rn-modal-dropdown/blob/master/example/src/FormikExample.tsx).
It will help you also, you can add an outline by changing the _mode="outlined"_ basically this component extended version of react-native-paper.
Whatever the option you get in react-native-paper most of them are exposed here except a few which are making trouble for the component.

**Comment by zhrht** [comment]
I changed the mode to outlined to show the border of the dropdown but there's a problem that when I choose something from the list the label is going up across the border line unlike the normal **TextInput** in react-native-paper it reserve empty space for the label  , do you have any idea how to fix that  because I searched but I I couldn't figure out since the border cannot be controlled using styleSheet.

This is the normal **TextInput** in react-native-paper:

![image](https://user-images.githubusercontent.com/62385306/108725721-b8dbdd80-7537-11eb-892d-f1281bdcc43f.png)

And this is the dropdown list when I enable mode="outlined":

![IMG_8400](https://user-images.githubusercontent.com/62385306/108725756-c1ccaf00-7537-11eb-862b-fd7324bd3328.jpg)

**Comment by srk-sharingan** [comment]
Looks like this issue happens react-native-paper itself, I will have a look into this.

**Comment by AlacranBlanco** [comment]
Im having the same problem.

**Comment by VennilaPugazhenthi** [comment]
I am also facing the same issue. The outlined mode isn't working properly.

**Comment by srk-sharingan** [comment]
Use the latest version v1.4, the issue has been fixed in that.
