### ISSUE TITLE
Arrow Icon not showing up (Unrecognized font family 'Material Design Icons')

### ISSUE THREAD

**Issue by ELMAJOULI** [srk-sharingan/sharingan-rn-modal-dropdown#27]
Hello, hope you're doing well, first things first, I would like to think you for your effort to provide us with a very useful material.
i've followed up the installation instructions. But when using MultiselectDropdown component i face Unrecognized font family 'Material Design Icons' issue.

`   <MultiselectDropdown
                data={skillLevelData}
                value={selectedSkillLevel}
                onChange={setSelectedSkillLevel}
                textInputStyle={Style.textInputDD}
                chipStyle={Style.chipStyle}
                underlineColor={'transparent'}
                emptySelectionText={i18n.t(translation.selectSkillLevel.id)}
              />
`

`  textInputDD: {
    height: height * 0.06,
    fontSize: 12,
  },
  chipStyle: {
    display: 'none',
  },`
![simulator_screenshot_2BD12EBA-E3F2-4EF7-B28F-41B3FC91CFBA](https://user-images.githubusercontent.com/33967002/118643776-e6ea5a00-b7d4-11eb-8001-df7c9eac7c98.png)
<img width="357" alt="Screen Shot 2021-05-18 at 12 32 04" src="https://user-images.githubusercontent.com/33967002/118643941-1ac57f80-b7d5-11eb-8f8d-dbfde185bea4.png">

"react-native": "0.63.4"
"sharingan-rn-modal-dropdown": "1.3.1"

**Comment by mmaass** [comment]
Hi, this issue seems to be related to react-native-vector-icons. You might checkout the issues over there for help.
e.g. https://github.com/oblador/react-native-vector-icons/issues/135

**Comment by srk-sharingan** [comment]
Please install react-native-vector-icon and link the material design font icon to your project that should fix the issue. The reasons for not having the icons out of the box:
- The configuration of icons vary based on the individual need.
- And to reduce the package size.
