### ISSUE TITLE
Disable an item in the dropdown.

### ISSUE THREAD

**Issue by mcelliott** [srk-sharingan/sharingan-rn-modal-dropdown#28]
Is there a way to disable an item in the dropdown? 

The `IDropdownItemProps` have a `disabled` prop but there doesn't seem to be a way to pass this into the items.

I would like to set disabled and style items in the dropdown options. 

Any help is appreciated.

**Comment by srk-sharingan** [comment]
I am working on it. I will expose an attribute **_disabled_** in the item object that should handle it.

**Comment by srk-sharingan** [comment]
You can disable the item by adding the `disabled` attribute in the item object :
Example: 
`{
  "value": "1",
  "label": "Tiger Nixon",
  "employee_salary": "320800",
  "employee_age": "61",
  "avatarSource": require("./ddicon.png"),
  "disabled": true // disable the item
}`
