### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by mmaass** [srk-sharingan/sharingan-rn-modal-dropdown#29]
Greetings stranger!

On my quest to localize the MultiselectDropdown I discovered there is no way to replace the string which informs about the number of selected items. It's hardcoded to **(count) selected**
<img width="310" alt="Screenshot 2021-06-30 at 12 11 43" src="https://user-images.githubusercontent.com/576477/123943418-6d7d8400-d99c-11eb-8dd1-702d3a55e5f3.png">

I would propose to have the suffix "selected" to be localizable via a prop, as it is the case with other texts/labels. 

I can create a PR, if you wouldn't mind.

**Comment by srk-sharingan** [comment]
I might have missed that, Please create a PR.
