### ISSUE TITLE
multiline text is not working in textInput

### ISSUE THREAD

**Issue by harsha1439** [srk-sharingan/sharingan-rn-modal-dropdown#33]
1. When selected item from dropdown the item text is not aligning in textinput. Applied all the CSS stylings for **textInputStyle** prop to align the text, still didn't work.
<img width="315" alt="Screen Shot 2021-08-12 at 1 01 00 PM" src="https://user-images.githubusercontent.com/12248640/129237886-018cbb61-3ee7-4b7e-ab88-1d690ee4a253.png">

2. When set height it is showing whole text in single line also increasing height is not aligning the text in two lines. Below screenshot shows the text in single line where remaining portion of the text is hidden.

<img width="315" alt="Screen Shot 2021-08-12 at 1 03 55 PM" src="https://user-images.githubusercontent.com/12248640/129238294-7e4d9138-d0ce-4193-8efb-7b6a2acbd9b5.png">

 3. At last I went inside the https://github.com/srk-sharingan/sharingan-rn-modal-dropdown/blob/master/src/Dropdown/index.tsx file and added on more prop to TextInput (Attaching scrrenshot)
 <img width="401" alt="Screen Shot 2021-08-12 at 1 06 37 PM" src="https://user-images.githubusercontent.com/12248640/129238753-99326487-7196-4f2b-9af7-0fbce450a07f.png">

The above code change is showing the long text in two lines. screenshot below
<img width="308" alt="Screen Shot 2021-08-12 at 1 10 16 PM" src="https://user-images.githubusercontent.com/12248640/129239134-7b70b014-dd3d-47e6-b6b0-024439951a4e.png">

The requirement is to align the long text into multiline which is not working by styling **textInputStyle** prop. any suggestions to achieve that, also if possible can you include multiline prop to TextInput.

**Comment by srk-sharingan** [comment]
Thanks for the details, I will expose props for this.

**Comment by srk-sharingan** [comment]
I have introduced the props `multiline={multiline}` please use it to enable the multiline option for textInput
