### ISSUE TITLE
TextInput OutlineColor

### ISSUE THREAD

**Issue by harsha1439** [srk-sharingan/sharingan-rn-modal-dropdown#37]
Please include OutlineColor prop to change the outline color for textinput. With the given props I am unable to change textinput border color for mode: 'outlined'.

If there is any other way to change TextInput border color, please do share it.

**Comment by srk-sharingan** [comment]
You can use the theme prop, check out the react-native-paper TextInput document that should help you to change the input border color.

**Comment by harsha1439** [comment]
That worked. Thank you.

**Comment by NikkiDev** [comment]
> That worked. Thank you.

Hello there,
can you please provide example, how to apply  outlineColor  thru the theme prop? i tried and mine doesnt work... thanks in advance

**Comment by selvamk-js** [comment]
If you are using react-native-paper check out their documents about customization using a theme if you set outline color for the app-level theme that will change the TextInput outline color.

**Comment by NikkiDev** [comment]
> customization using a theme

thanks for reply

**Comment by dadablaze2000** [comment]
Please Help, How can I change the outline color without using the paper theme
